"""phase7 gala dinner

Revision ID: 0276d0698c61
Revises: dfc87661f640
Create Date: 2026-09-12 00:22:29.792448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0276d0698c61'
down_revision: Union[str, None] = 'dfc87661f640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gala_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stage_label', sa.String(length=100), nullable=False),
    sa.Column('turn_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('hold_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('seat_quota_rule', sa.Enum('by_team_size', 'fixed', name='gala_seat_quota_rule', native_enum=False, length=20), nullable=False),
    sa.Column('fixed_quota', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('setup', 'drawing', 'in_progress', 'finished', name='gala_config_status', native_enum=False, length=20), nullable=False),
    sa.Column('draw_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gala_configs_event_id'), 'gala_configs', ['event_id'], unique=False)
    op.create_table('gala_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('shape', sa.Enum('round', 'rect', name='gala_table_shape', native_enum=False, length=20), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gala_tables_event_id'), 'gala_tables', ['event_id'], unique=False)
    op.create_table('gala_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('seat_quota', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'active', 'done', 'skipped', 'expired', name='gala_turn_status', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gala_turns_event_id'), 'gala_turns', ['event_id'], unique=False)
    op.create_table('gala_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('available', 'held', 'confirmed', 'blocked', name='gala_seat_status', native_enum=False, length=20), nullable=False),
    sa.Column('held_by_team_id', sa.Integer(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['held_by_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['gala_tables.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gala_seats_table_id'), 'gala_seats', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gala_seats_table_id'), table_name='gala_seats')
    op.drop_table('gala_seats')
    op.drop_index(op.f('ix_gala_turns_event_id'), table_name='gala_turns')
    op.drop_table('gala_turns')
    op.drop_index(op.f('ix_gala_tables_event_id'), table_name='gala_tables')
    op.drop_table('gala_tables')
    op.drop_index(op.f('ix_gala_configs_event_id'), table_name='gala_configs')
    op.drop_table('gala_configs')
    # ### end Alembic commands ###
