"""phase2 registrations and email notification

Revision ID: 77d4165ffb56
Revises: b034e0021cd9
Create Date: 2026-09-11 23:34:04.381495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d4165ffb56'
down_revision: Union[str, None] = 'b034e0021cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'failed', name='email_outbox_status', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_outbox_dedupe_key'), 'email_outbox', ['dedupe_key'], unique=True)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.String(length=10000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_code'), 'email_templates', ['code'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'cancelled', name='registration_status', native_enum=False, length=20), nullable=False),
    sa.Column('is_participating', sa.Boolean(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('agreed_terms_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.Column('wish_note', sa.String(length=2000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'employee_id', name='uq_registration_event_employee')
    )
    op.create_index(op.f('ix_registrations_employee_id'), 'registrations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.create_table('registration_transport_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('is_needed', sa.Boolean(), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leg_id'], ['transport_legs.id'], ),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'leg_id', name='uq_transport_need_reg_leg')
    )
    op.create_index(op.f('ix_registration_transport_needs_registration_id'), 'registration_transport_needs', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_transport_needs_registration_id'), table_name='registration_transport_needs')
    op.drop_table('registration_transport_needs')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_employee_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_email_templates_code'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_outbox_dedupe_key'), table_name='email_outbox')
    op.drop_table('email_outbox')
    # ### end Alembic commands ###
