"""phase5 buses and bus allocation

Revision ID: a29b9e99f105
Revises: 7d32cd63b55f
Create Date: 2026-09-12 00:05:05.000538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29b9e99f105'
down_revision: Union[str, None] = '7d32cd63b55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('gather_at', sa.DateTime(), nullable=True),
    sa.Column('depart_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('leader_employee_id', sa.Integer(), nullable=True),
    sa.Column('leader_name', sa.String(length=200), nullable=True),
    sa.Column('leader_phone', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['leader_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leg_id'], ['transport_legs.id'], ),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_event_id'), 'buses', ['event_id'], unique=False)
    op.create_index(op.f('ix_buses_leg_id'), 'buses', ['leg_id'], unique=False)
    op.create_table('bus_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('auto', 'manual', 'import', name='bus_assignment_source', native_enum=False, length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=100), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['leg_id'], ['transport_legs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'employee_id', 'leg_id', name='uq_bus_assignment')
    )
    op.create_index(op.f('ix_bus_assignments_bus_id'), 'bus_assignments', ['bus_id'], unique=False)
    op.create_index(op.f('ix_bus_assignments_employee_id'), 'bus_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bus_assignments_event_id'), 'bus_assignments', ['event_id'], unique=False)
    op.create_index(op.f('ix_bus_assignments_leg_id'), 'bus_assignments', ['leg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_assignments_leg_id'), table_name='bus_assignments')
    op.drop_index(op.f('ix_bus_assignments_event_id'), table_name='bus_assignments')
    op.drop_index(op.f('ix_bus_assignments_employee_id'), table_name='bus_assignments')
    op.drop_index(op.f('ix_bus_assignments_bus_id'), table_name='bus_assignments')
    op.drop_table('bus_assignments')
    op.drop_index(op.f('ix_buses_leg_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_event_id'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
