"""phase3 flights and flight allocation

Revision ID: d94e7ec2254e
Revises: 77d4165ffb56
Create Date: 2026-09-11 23:48:08.645405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94e7ec2254e'
down_revision: Union[str, None] = '77d4165ffb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('flight_code', sa.String(length=50), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='flight_direction', native_enum=False, length=20), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('depart_at', sa.DateTime(), nullable=True),
    sa.Column('arrive_at', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_event_id'), 'flights', ['event_id'], unique=False)
    op.create_table('flight_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='flight_direction', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('auto', 'manual', 'import', name='assignment_source', native_enum=False, length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=100), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'employee_id', 'direction', name='uq_flight_assignment')
    )
    op.create_index(op.f('ix_flight_assignments_employee_id'), 'flight_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_flight_assignments_event_id'), 'flight_assignments', ['event_id'], unique=False)
    op.create_index(op.f('ix_flight_assignments_flight_id'), 'flight_assignments', ['flight_id'], unique=False)
    op.create_table('allocation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('flight', 'bus', name='allocation_run_type', native_enum=False, length=20), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='allocation_run_status', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_runs_event_id'), 'allocation_runs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocation_runs_event_id'), table_name='allocation_runs')
    op.drop_table('allocation_runs')
    op.drop_index(op.f('ix_flight_assignments_flight_id'), table_name='flight_assignments')
    op.drop_index(op.f('ix_flight_assignments_event_id'), table_name='flight_assignments')
    op.drop_index(op.f('ix_flight_assignments_employee_id'), table_name='flight_assignments')
    op.drop_table('flight_assignments')
    op.drop_index(op.f('ix_flights_event_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
